name: MediaService
options:
  bundleIdPrefix: com.rosberry
targets:
  MediaService:
    type: framework
    platform: iOS
    sources: [Sources/MediaService]
    info:
      path: MediaService.xcodeproj/MediaService.plist
  MediaServiceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Tests/MediaServiceTests]
    info:
      path: MediaService.xcodeproj/MediaServiceTests.plist
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
  Example:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Sources/Example]
    info:
      path: MediaService.xcodeproj/Example.plist
    dependencies:
      - target: MediaService
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
